name: CI - Build & Push to Quay

on:
  push:
    paths:
      - "Containerfile"
      - ".github/workflows/ci.yml"
  workflow_dispatch:

env:
  REGISTRY: quay.io
  IMAGE_NS: mag0225
  IMAGE_NAME: jake-fedora-bootc
  TAG_MAIN: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Quay
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Compute tag
        id: meta
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            TAG="${{ env.TAG_MAIN }}"
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            TAG="${{ github.ref_name }}"
          else
            TAG="$(echo "${{ github.ref_name }}" | tr '/' '-')"
          fi
          echo "image=${{ env.REGISTRY }}/${{ env.IMAGE_NS }}/${{ env.IMAGE_NAME }}:${TAG}" >> $GITHUB_OUTPUT

      - name: Build and Push (root Containerfile)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Containerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.image }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Show pushed image
        run: echo "Pushed ${{ steps.meta.outputs.image }}"
